### PR TITLE
Update pyproject.toml - allow higher rich version

### PR DESCRIPTION
**Pull request by cshaley**
This pull request makes the following changes:
* changes rich ^10.10.0 to rich >=10.10.0

(If there are changes to user behavior in general, please make sure to
update the docs, as well)

It relates to the following issue #s:
* Addressing issues #127 #143

### CODE REVIEW

**Comment by rxm7706** [comment]
Hi @bhamail 
cc. @madpah @bollwyvl @maarre @gregegg

Could you consider reviewing and merging this PR please. 
A new release will enable all of us again with jake !
Thanks & Regards.

**Review by bhamail — APPROVED** [review]
LGTM, +1.
Also, thanks for being persistent with the reminder pings!

**Comment by bhamail** [comment]
> Thank you @bhamail - It looks like we need an approval to release & publish to pypi. https://app.circleci.com/pipelines/github/sonatype-nexus-community/jake/1339/workflows/26dbe621-5002-4e92-b56f-8d56795f2767

Doh! Yes indeed. Button mashed. Fingers crossed.

**Comment by cshaley** [comment]
@bhamail As I understand, versioning of jake is automated.  It looks like [the build tried to publish 3.0.1 again](https://app.circleci.com/pipelines/github/sonatype-nexus-community/jake/1340/workflows/558e03cd-d18d-420a-b5e0-a85757427c1d/jobs/3050), and it failed.

What's the right next step to get jake updated with the new dependency specification?

**Comment by bhamail** [comment]
@cshaley I tried manually incrementing the version and doing a manual release. I don't see errors in the build, but I don't see the new release  in pypi either. Please ping again if nothing shows up by tomorrow.

**Comment by rxm7706** [comment]
@bhamail - looks like no release published on PyPi - https://pypi.org/project/jake/#history or even on github https://github.com/sonatype-nexus-community/jake/releases - the semantic release step - shows no log - but on the prior step - i do see a warning on poetry-lock being out of date. That shouldn't have prevented the release..

https://app.circleci.com/pipelines/github/sonatype-nexus-community/jake/1341/workflows/26a9d3dc-29e4-4a23-9e23-e15f72674a21/jobs/3061

**Comment by cshaley** [comment]
@bhamail https://app.circleci.com/pipelines/github/sonatype-nexus-community/jake/1342/workflows/fbc35697-a32c-4121-a5e4-7a9049b46ac6/jobs/3072
It looks like it's working, but not showing up in pypi! 

I'm thinking the `semantic-release publish` step is failing silently.  It looks like it also failed (not silently) for all attempts to publish jake 3.0.1 - at least the ones in the publish history that I can see eg [1335](https://app.circleci.com/pipelines/github/sonatype-nexus-community/jake/1335/workflows/d5f12c1b-4c78-4921-ba0f-ab99d70349de/jobs/3002) and [1340](https://app.circleci.com/pipelines/github/sonatype-nexus-community/jake/1340/workflows/558e03cd-d18d-420a-b5e0-a85757427c1d/jobs/3050).  So I'm not too sure how 3.0.1 got published to pypi unless it was before the visible history on circleci.  

@bhamail thoughts on next steps?  It looks like [we could](https://python-semantic-release.readthedocs.io/en/latest/troubleshooting.html#increasing-verbosity) do `semantic-release -v publish` or `semantic-release -vv publish` to get it to output more information.

**Comment by cshaley** [comment]
@bhamail thanks for taking the next step.  

I think I diagnosed it.  [python-semantic-release has breaking changes in v8](https://python-semantic-release.readthedocs.io/en/latest/migrating_from_v7.html).  

So two options:

1. Revert to `pip install "python-semantic-release<8"
2. Update commands to
 ```
semantic-release version
twine upload dist/* 
semantic-release publish
```

From reading the python-semantic-release docs linked above, I think jake's current process automatically handles version updates (i.e. v7 of semantic-release updates jake's version in github as part of the publish command).  So I think we need all three lines above.
Note: this probably means adding twine to the pip install line too.  I'll raise a PR with approach 2.

**Comment by gregegg** [comment]
> Hi @bhamail cc. @madpah @bollwyvl @maarre @gregegg
> 
> Could you consider reviewing and merging this PR please. A new release will enable all of us again with jake ! Thanks & Regards.

Thanks everyone!

**Pull request merged**
